stages:
  - test
  - package

variables:
  PYTHONUNBUFFERED: "1"
  PYTHONDONTWRITEBYTECODE: "1"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PIP_ROOT_USER_ACTION: "ignore"

test:tox:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: python:$PYTHON_VERSION
  parallel:
    matrix:
      - PYTHON_VERSION:
        - "3.7"
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
  cache:
    key: pip-$PYTHON_VERSION
    paths:
      - .cache/pip
  before_script:
    - git fetch --unshallow --all
  script:
    - python3 --version
    - python3 -m pip install --upgrade pip wheel tox
    - tox
  artifacts:
    when: always
    name: "$CI_COMMIT_REF_SLUG"
    paths:
      - dist/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: dist/coverage.xml
      junit: dist/junit.xml
  coverage: /(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/

package:pypi:
  stage: package
  rules:
    - if: $CI_COMMIT_TAG
  image: python:3.11
  script:
    - python3 -m pip install --upgrade pip wheel build twine
    - python3 -m build
    - twine upload --non-interactive dist/*
    # Set these envvars in [settings] > [ci/cd] > [variables]:
    # - TWINE_USERNAME: __token__
    # - TWINE_PASSWORD: pypi-...
