[tool.black]
line_length = 88
target_version = ["py36"]

[tool.isort]
src_paths = ["commit_message_validator"]
line_length = 88
profile = "black"
force_single_line = true
force_sort_within_sections = true
case_sensitive = false
