This is the subject line of the commit

The body of the commit message starts after a blank line. It contains just
about any random text, but each line should not exceed 100 characters. Really
there is no good reason for any body line to exceed 72 characters (80 column
display with an 8 character tab leading the line) except in the case of a long
URL that is embedded in the message.

Change-Id: Ifcd397165df1cbf9fa04f2044e1bb33ad7414d8d
Signed-off-by: Someone awesome <awesome@example.net>
